name: firebase_ui_auth
description: Pre-built widgets library that are integrated with the variety of the Firebase Auth providers.
version: 1.13.0
repository: https://github.com/firebase/FirebaseUI-Flutter/tree/master/packages/firebase_ui_auth
homepage: https://github.com/firebase/FirebaseUI-Flutter/tree/master/packages/firebase_ui_auth
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  email_validator: ^2.1.17
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_dynamic_links: ^5.4.8
  firebase_ui_localizations:
    git:
      url: https://github.com/shebnik/FirebaseUI-Flutter.git
      ref: main
      path: packages/firebase_ui_localizations
  firebase_ui_oauth:
    git:
      url: https://github.com/shebnik/FirebaseUI-Flutter.git
      ref: main
      path: packages/firebase_ui_oauth
  firebase_ui_shared: 
    git:
      url: https://github.com/shebnik/FirebaseUI-Flutter.git
      ref: main
      path: packages/firebase_ui_shared
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  meta: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4

false_secrets:
  - "/example/**/google-services.json"
  - "/example/**/firebase_options.dart"
  - "/example/**/GoogleService-Info.plist"
  - "example/lib/config.dart"

flutter:
